### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'init_cfg'

### ISSUE THREAD

**Issue by smurf-1119** [yzd-v/FGD#33]
When I run the test code, I meet this problem:

Traceback (most recent call last):
  File "tools/train.py", line 199, in <module>
    main()
  File "tools/train.py", line 172, in main
    test_cfg=student_cfg.get('test_cfg'))
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/distillation/builder.py", line 47, in build_distiller
    return build(cfg, DISTILLER, dict(teacher_cfg=teacher_cfg,student_cfg=student_cfg))
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/distillation/builder.py", line 29, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/distillation/distillers/detection_distiller.py", line 30, in __init__
    test_cfg=teacher_cfg.get('test_cfg'))
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/models/builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/models/detectors/retinanet.py", line 17, in __init__
    test_cfg, pretrained)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/models/detectors/single_stage.py", line 25, in __init__
    self.backbone = build_backbone(backbone)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/models/builder.py", line 39, in build_backbone
    return build(cfg, BACKBONES)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/root/miniconda3/envs/fgd/lib/python3.7/site-packages/mmdet/models/backbones/resnext.py", line 145, in __init__
    super(ResNeXt, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'init_cfg'

How can I fix it?

**Comment by yzd-v** [comment]
It seems your mmdet version doesn't meet your mmcv version.
